import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

export interface ReportHeaderOptions {
  companyName?: string;
  reportTitle: string;
  subtitle?: string;
  dateRangeStr?: string;
  generatedBy?: string;
  summaryCards?: { label: string; value: string }[];
}

/**
 * Common PDF Layout Builder with Brand Banner, Summary Cards, and Autotable
 */
export function generatePDFReport({
  companyName = 'SASA OFFICIAL',
  reportTitle,
  subtitle,
  dateRangeStr,
  generatedBy = 'Admin Portal',
  summaryCards = [],
  headers,
  rows,
  fileName = 'SASA_Report'
}: ReportHeaderOptions & {
  headers: string[];
  rows: (string | number)[][];
  fileName?: string;
}) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  const primaryColor = '#1E1E24';
  const goldAccent = '#D4AF37';

  // Header Banner
  doc.setFillColor(30, 30, 36); // Dark luxury background
  doc.rect(0, 0, 297, 28, 'F');

  // Brand Logo Text
  doc.setTextColor(212, 175, 55); // Gold
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(companyName, 14, 15);

  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'normal');
  doc.text('LUXURY FORMAL & PRET WEAR — OFFICIAL BUSINESS REPORT', 14, 22);

  // Date and Metadata on Right
  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  const dateText = `Date: ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}`;
  doc.text(dateText, 283, 14, { align: 'right' });
  doc.text(`Generated by: ${generatedBy}`, 283, 20, { align: 'right' });

  // Report Title Section
  let currentY = 36;
  doc.setTextColor(30, 30, 36);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(reportTitle.toUpperCase(), 14, currentY);

  if (subtitle || dateRangeStr) {
    currentY += 6;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    const subStr = [subtitle, dateRangeStr ? `Period: ${dateRangeStr}` : ''].filter(Boolean).join(' | ');
    doc.text(subStr, 14, currentY);
  }

  currentY += 8;

  // Summary KPI Cards (if any)
  if (summaryCards.length > 0) {
    const cardWidth = Math.min(60, (269 - (summaryCards.length - 1) * 4) / summaryCards.length);
    summaryCards.forEach((card, idx) => {
      const cardX = 14 + idx * (cardWidth + 4);
      doc.setFillColor(248, 246, 242);
      doc.setDrawColor(220, 210, 195);
      doc.roundedRect(cardX, currentY, cardWidth, 16, 2, 2, 'FD');

      doc.setFontSize(8);
      doc.setTextColor(120, 110, 95);
      doc.setFont('helvetica', 'bold');
      doc.text(card.label.toUpperCase(), cardX + 4, currentY + 5);

      doc.setFontSize(11);
      doc.setTextColor(30, 30, 36);
      doc.setFont('helvetica', 'bold');
      doc.text(card.value, cardX + 4, currentY + 12);
    });

    currentY += 22;
  }

  // AutoTable Data Render
  autoTable(doc, {
    startY: currentY,
    head: [headers],
    body: rows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 30, 36],
      textColor: [212, 175, 55],
      fontStyle: 'bold',
      fontSize: 9,
      halign: 'left'
    },
    bodyStyles: {
      textColor: [40, 40, 40],
      fontSize: 8,
      cellPadding: 2.5
    },
    alternateRowStyles: {
      fillColor: [250, 248, 245]
    },
    styles: {
      overflow: 'linebreak',
      cellWidth: 'auto'
    },
    margin: { left: 14, right: 14, bottom: 20 },
    didDrawPage: (data) => {
      // Footer page numbering
      const totalPages = (doc as any).internal.getNumberOfPages();
      const currentPage = data.pageNumber;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${currentPage} of ${totalPages}`, 283, 202, { align: 'right' });
      doc.text('CONFIDENTIAL — SASA OFFICIAL INTERNAL REPORT', 14, 202);
    }
  });

  doc.save(`${fileName}_${new Date().toISOString().slice(0, 10)}.pdf`);
}

/**
 * Excel Export Generator using SheetJS (XLSX)
 */
export function generateExcelReport({
  companyName = 'SASA OFFICIAL',
  reportTitle,
  dateRangeStr,
  summaryCards = [],
  headers,
  rows,
  fileName = 'SASA_Report'
}: ReportHeaderOptions & {
  headers: string[];
  rows: (string | number)[][];
  fileName?: string;
}) {
  const worksheetData: (string | number)[][] = [];

  // Title block
  worksheetData.push([companyName.toUpperCase()]);
  worksheetData.push([reportTitle]);
  if (dateRangeStr) worksheetData.push([`Period: ${dateRangeStr}`]);
  worksheetData.push([`Generated On: ${new Date().toLocaleString()}`]);
  worksheetData.push([]);

  // Summary Cards block
  if (summaryCards.length > 0) {
    worksheetData.push(['--- REPORT SUMMARY ---']);
    summaryCards.forEach(c => {
      worksheetData.push([c.label, c.value]);
    });
    worksheetData.push([]);
  }

  // Headers & Rows
  worksheetData.push(headers);
  rows.forEach(r => worksheetData.push(r));

  const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);

  // Auto-fit column widths
  const colWidths = headers.map((h, i) => {
    let maxLen = String(h).length;
    rows.forEach(r => {
      const val = String(r[i] || '');
      if (val.length > maxLen) maxLen = val.length;
    });
    return { wch: Math.min(Math.max(maxLen + 3, 12), 40) };
  });

  worksheet['!cols'] = colWidths;

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');

  XLSX.writeFile(workbook, `${fileName}_${new Date().toISOString().slice(0, 10)}.xlsx`);
}
